@extends('layouts.app')
@section('title', 'Business Location Settings')
@section('content')
@php
$input = 'mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm focus:border-purple-500 focus:outline-none focus:ring-2 focus:ring-purple-100';
@endphp
@if(session('status'))<div class="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-800">{{ session('status') }}</div>@endif
<div class="mb-5"><h1 class="text-xl font-bold text-slate-900">Business Location Settings - Codeza ERP</h1><p class="mt-1 text-sm text-slate-500">Receipt and invoice settings for this location</p></div>
<section class="rounded-2xl border border-purple-100 bg-white shadow-sm"><div class="border-b border-purple-100 px-6 py-4"><h2 class="font-bold text-purple-700"><i class="bi bi-receipt"></i> Receipt Settings</h2></div><form method="POST" action="{{ route('business.locations.settings.update',$location) }}">@csrf @method('PUT')<div class="grid gap-5 p-6 md:grid-cols-2"><label class="text-xs font-bold text-slate-700">Auto print invoice after finalizing:<select name="auto_print_invoice" class="{{ $input }}"><option value="1" @selected($setting->auto_print_invoice)>Yes</option><option value="0" @selected(!$setting->auto_print_invoice)>No</option></select></label><label class="text-xs font-bold text-slate-700">Receipt Printer Type:*<select id="printer-type" name="printer_type" class="{{ $input }}"><option value="browser" @selected($setting->printer_type==='browser')>Browser Based Printing</option><option value="configured" @selected($setting->printer_type==='configured')>Use Configured Receipt Printer</option></select></label><label id="printer-field" class="hidden text-xs font-bold text-slate-700">Receipt Printer:*<select name="receipt_printer_id" class="{{ $input }}"><option value="">Please Select</option>@foreach($printers as $printer)<option value="{{ $printer->id }}" @selected($setting->receipt_printer_id===$printer->id)>{{ $printer->name }}</option>@endforeach</select><span class="mt-1 block font-normal text-slate-500">Add configured printers from Printer Settings.</span></label><label class="text-xs font-bold text-slate-700">Invoice layout:*<select name="invoice_layout_id" class="{{ $input }}">@foreach($layouts as $layout)<option value="{{ $layout->id }}" @selected($setting->invoice_layout_id===$layout->id)>{{ $layout->name }}</option>@endforeach</select></label><label class="text-xs font-bold text-slate-700">Invoice scheme:*<select name="invoice_scheme_id" class="{{ $input }}">@foreach($schemes as $scheme)<option value="{{ $scheme->id }}" @selected($setting->invoice_scheme_id===$scheme->id)>{{ $scheme->name }}</option>@endforeach</select></label></div><div class="flex justify-end border-t border-purple-100 px-6 py-4"><button class="rounded-xl bg-purple-600 px-5 py-2.5 text-xs font-bold text-white hover:bg-purple-700">Update</button></div></form></section>
@endsection
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const type=document.querySelector('#printer-type'),field=document.querySelector('#printer-field'),sync=()=>field.classList.toggle('hidden',type.value!=='configured');type.addEventListener('change',sync);sync()})</script>@endpush