@extends('layouts.app')
@section('title',$bom->exists?'Edit Recipe':'New Recipe')
@section('content')
@include('serials.common')
<div class="mb-5"><p class="text-xs font-bold uppercase tracking-widest text-purple-600">Bill of Materials</p><h1 class="text-2xl font-black">{{ $bom->exists?'Edit recipe':'Create recipe' }}</h1><p class="text-sm text-slate-500">Quantities below are for the base output quantity. Production orders scale them automatically.</p></div>
<form method="POST" action="{{ $bom->exists?route('manufacturing.boms.update',$bom):route('manufacturing.boms.store') }}">@csrf @if($bom->exists)@method('PUT')@endif
<section class="serial-card"><div class="serial-grid"><div><label>Recipe code *</label><input name="code" required maxlength="40" value="{{ old('code',$bom->code) }}" placeholder="BOM-PACK-RICE-01"></div><div><label>Finished product *</label><select name="product_id" required><option value="">Select product</option>@foreach($outputs as $p)<option value="{{ $p->id }}" @selected(old('product_id',$bom->product_id)==$p->id)>{{ $p->name }} ({{ $p->code }})</option>@endforeach</select></div><div><label>Base output quantity *</label><input type="number" min="0.0001" step="0.0001" name="output_quantity" required value="{{ old('output_quantity',$bom->output_quantity?:1) }}"></div><div class="flex items-center pt-6"><input type="hidden" name="is_active" value="0"><label><input type="checkbox" name="is_active" value="1" @checked(old('is_active',$bom->exists?$bom->is_active:true))> Active recipe</label></div><div class="wide"><label>Notes</label><textarea name="notes" maxlength="2000">{{ old('notes',$bom->notes) }}</textarea></div></div></section>
<section class="serial-card"><div class="mb-4 flex items-center justify-between"><div><h2>Recipe materials</h2><p class="text-sm text-slate-500">Only active Single and Variable products marked “Use as manufacturing raw material” appear here. Choose the exact variation when required.</p></div><button type="button" id="add-item" class="serial-btn serial-secondary">+ Add material</button></div><div id="items" class="space-y-3"></div></section>
<div class="flex justify-between"><a href="{{ route('manufacturing.boms.index') }}" class="serial-btn serial-secondary">Cancel</a><button class="serial-btn">Save recipe</button></div></form>
<template id="item-template"><div class="item-row grid gap-3 rounded-xl border p-3 md:grid-cols-[1fr_1fr_180px_auto]"><div><label>Raw material *</label><select class="item-product" required><option value="">Select material</option>@foreach($materials as $m)<option value="{{ $m->id }}">{{ $m->name }} ({{ $m->code }}) · {{ ucfirst($m->product_type) }} · {{ $m->unit?->short_name }}</option>@endforeach</select></div><div class="variant-wrap" hidden><label>Variation *</label><select class="item-variant"><option value="">Select exact variation</option></select></div><div><label>Quantity *</label><input class="item-qty" type="number" min="0.0001" step="0.0001" required></div><button type="button" class="remove-row self-end py-2 text-rose-600">Remove</button></div></template>
@endsection
@php
$materialOptions = $materials->mapWithKeys(function ($material) {
    return [$material->id => ['type' => $material->product_type, 'variants' => $material->variants->map(function ($variant) {
        return ['id' => $variant->id, 'label' => ($variant->value ?: 'Variant').' ('.$variant->sku.')'];
    })->values()]];
});
$existingItems = old('items', $bom->items->map(fn ($item) => ['product_id' => $item->product_id, 'product_variant_id' => $item->product_variant_id, 'quantity' => $item->quantity])->values());
@endphp
@push('scripts')<script>AppPage.ready(()=>{let i=0;const box=document.getElementById('items'),materials=@json($materialOptions),existing=@json($existingItems);function add(v={}){const n=document.getElementById('item-template').content.firstElementChild.cloneNode(true),x=i++,product=n.querySelector('.item-product'),variant=n.querySelector('.item-variant'),wrap=n.querySelector('.variant-wrap');product.name=`items[${x}][product_id]`;variant.name=`items[${x}][product_variant_id]`;n.querySelector('.item-qty').name=`items[${x}][quantity]`;function sync(selected=''){const m=materials[product.value];variant.innerHTML='<option value="">Select exact variation</option>';(m?.variants||[]).forEach(o=>variant.add(new Option(o.label,o.id)));const variable=m?.type==='variable';wrap.hidden=!variable;variant.required=variable;variant.disabled=!variable;if(selected)variant.value=selected}product.value=v.product_id||'';sync(v.product_variant_id||'');product.onchange=()=>sync();n.querySelector('.item-qty').value=v.quantity||'';n.querySelector('.remove-row').onclick=()=>n.remove();box.append(n)}document.getElementById('add-item').onclick=()=>add();existing.length?existing.forEach(add):add()});</script>@endpush
