@extends('layouts.app')
@section('title','New Manufacturing Order')
@section('content')
@include('serials.common')
<style>.mfg-step{display:flex;align-items:center;gap:10px;flex:1;color:#64748b}.mfg-step:not(:last-child)::after{content:"";height:3px;flex:1;background:#e2e8f0;border-radius:9px}.mfg-step button{width:46px;height:46px;border-radius:999px;background:#e2e8f0;font-weight:900}.mfg-step.active button,.mfg-step.done button{background:#7c3aed;color:#fff}.mfg-step.done:not(:last-child)::after{background:#7c3aed}.wizard-panel{display:none}.wizard-panel.active{display:block}.mfg-product-search{position:relative}.mfg-product-search input{width:100%;border:1px solid #cbd5e1;border-radius:12px;background:#fff;padding:10px 38px 10px 12px}.mfg-product-search input:focus{border-color:#7c3aed;box-shadow:0 0 0 2px rgb(124 58 237/.18);outline:none}.mfg-product-search i{pointer-events:none;position:absolute;right:13px;top:13px;color:#64748b}.mfg-product-results{position:absolute;z-index:90;top:calc(100% + 5px);left:0;right:0;max-height:260px;overflow:auto;border:1px solid #cbd5e1;border-radius:12px;background:#fff;padding:5px;box-shadow:0 18px 38px rgb(15 23 42/.18)}.mfg-product-option{display:block;width:100%;border-radius:9px;padding:10px;text-align:left;font-size:13px}.mfg-product-option:hover,.mfg-product-option.active{background:#f3e8ff;color:#6d28d9}.mfg-product-empty{padding:12px;text-align:center;color:#94a3b8}.mfg-hidden-select{position:absolute!important;width:1px!important;height:1px!important;overflow:hidden!important;clip:rect(0,0,0,0)!important}</style>
<div class="mb-6 flex flex-wrap items-center justify-between gap-3 rounded-2xl p-6 shadow-xl" style="background:linear-gradient(110deg,#0f172a,#312e81,#6b21a8);color:#fff"><div><p class="text-xs font-bold uppercase tracking-widest" style="color:#a7f3d0">Production wizard</p><h1 class="text-2xl font-black" style="color:#fff">New Manufacturing Order</h1><p class="text-sm" style="color:#dbeafe">Choose product and recipe â†’ check materials and costs â†’ create draft order</p></div><a href="{{ route('manufacturing.boms.index') }}" class="rounded-xl bg-white/15 px-4 py-2 font-bold text-white">Manage recipes</a></div>
<div id="mfg-steps" class="mb-6 flex rounded-2xl border bg-white p-5 shadow-sm"><div class="mfg-step active" data-step="1"><button type="button">1</button><span class="hidden font-bold sm:block">Product & recipe</span></div><div class="mfg-step" data-step="2"><button type="button">2</button><span class="hidden font-bold sm:block">Materials & cost</span></div><div class="mfg-step" data-step="3"><button type="button">3</button><span class="hidden font-bold sm:block">Review & draft</span></div></div>
<form id="mfg-form" method="POST" action="{{ route('manufacturing.store') }}">@csrf
<section class="wizard-panel active serial-card" data-panel="1"><div class="mb-5 flex flex-wrap items-start justify-between gap-3"><div><h2 class="text-xl font-black">1. What are you making?</h2><p class="text-sm text-slate-500">Search and choose the finished product, then select its recipe and enter the production details.</p></div><div class="rounded-xl bg-slate-100 px-4 py-2 text-right"><small class="block text-slate-500">Manufacturing Order ID</small><b class="text-purple-700">Generated automatically on save</b></div></div><div class="serial-grid"><div><label>Finished product *</label><div class="mfg-product-search"><input id="product-search" type="search" autocomplete="off" placeholder="Search product name or SKU/code..." role="combobox" aria-controls="product-results" aria-expanded="false"><i class="bi bi-chevron-down"></i><div id="product-results" class="mfg-product-results" role="listbox" hidden></div></div><select id="product_id" name="product_id" required class="mfg-hidden-select" tabindex="-1"><option value="">Select a finished product</option>@foreach($outputs as $p)<option value="{{ $p->id }}" data-name="{{ $p->name }}" data-unit="{{ $p->unit?->short_name }}" data-selling="{{ $p->selling_price }}" data-serial="{{ $p->enable_serial?1:0 }}" data-expiry="{{ $p->expiry_period }}" data-expiry-type="{{ $p->expiry_period_type }}">{{ $p->name }} ({{ $p->code }}){{ $p->enable_serial?' Â· Serial tracked':'' }}</option>@endforeach</select><small class="text-slate-500">Active, stock-managed Single products appear here.</small></div><div><label>Bill of Materials / Recipe *</label><select id="bill_of_material_id" name="bill_of_material_id" required disabled><option value="">Select product first</option></select><small id="bom-help" class="text-slate-500"></small></div><div><label>Production warehouse *</label><select id="location_id" name="location_id" required><option value="">Select warehouse</option>@foreach($locations as $l)<option value="{{ $l->id }}">{{ $l->name }}</option>@endforeach</select></div><div><label>Quantity to produce *</label><input id="quantity" name="quantity" type="number" min="0.0001" step="0.0001" required><small id="quantity-help" class="text-slate-500"></small></div><div><label>Manufacturing date *</label><input id="manufactured_at" name="manufactured_at" type="date" max="{{ now()->toDateString() }}" value="{{ now()->toDateString() }}" required></div><div><label>Expiry date</label><input id="expires_at" name="expires_at" type="date"></div><div class="wide"><label>Notes</label><textarea name="notes" rows="2" maxlength="2000"></textarea></div></div><div class="mt-5 text-right"><button type="button" class="serial-btn next-step" data-next="2">Continue to materials <i class="bi bi-arrow-right"></i></button></div></section>
<section class="wizard-panel serial-card" data-panel="2"><h2 class="text-xl font-black">2. Recipe materials and manufacturing expenses</h2><p class="mb-4 text-sm text-slate-500">Material quantities scale automatically from the recipe and output quantity.</p><div id="recipe-lines" class="overflow-x-auto"></div><hr><div class="mb-3 flex justify-between"><h3 class="font-bold">Additional expenses</h3><button type="button" id="add-expense" class="serial-btn serial-secondary">+ Add expense</button></div><div id="expense-lines" class="space-y-2"></div><div class="mt-5 flex justify-between"><button type="button" class="serial-btn serial-secondary next-step" data-next="1">Back</button><button type="button" class="serial-btn next-step" data-next="3">Review order <i class="bi bi-arrow-right"></i></button></div></section>
<section class="wizard-panel serial-card" data-panel="3"><h2 class="text-xl font-black">3. Review and create draft</h2><p class="mb-4 text-sm text-slate-500">Review the calculated cost, set the finished product selling price, and create the draft order.</p><div id="review"></div><div class="mt-4 rounded-xl border border-purple-200 bg-purple-50 p-4"><label for="selling_price" class="font-bold text-purple-900">Finished product selling price *</label><input id="selling_price" name="selling_price" type="number" min="0" step="0.0001" required class="mt-2 bg-white"><small class="mt-2 block text-purple-700">The product's current selling price is filled automatically. Change it here if this production batch needs a different price.</small></div><div class="mt-5 flex justify-between"><button type="button" class="serial-btn serial-secondary next-step" data-next="2">Back</button><button type="submit" id="process-button" class="serial-btn"><i class="bi bi-file-earmark-check"></i> Create draft order</button></div></section>
</form>
<template id="expense-template"><div class="expense-row grid gap-3 rounded-xl border p-3 md:grid-cols-[1fr_220px_auto]"><input class="expense-name" maxlength="150" placeholder="Labour, electricity, packing..."><input class="expense-amount" type="number" min="0" step="0.0001" placeholder="Amount"><button type="button" class="remove-row text-rose-600">Remove</button></div></template>
@endsection
@push('scripts')<script>
AppPage.ready(()=>{const boms=@json($bomData),steps=[...document.querySelectorAll('.mfg-step')],panels=[...document.querySelectorAll('.wizard-panel')],product=document.getElementById('product_id'),bomSelect=document.getElementById('bill_of_material_id'),qty=document.getElementById('quantity'),expenses=document.getElementById('expense-lines');let expenseIndex=0;
const productSearch=document.getElementById('product-search'),productResults=document.getElementById('product-results'),productOptions=[...product.options].filter(o=>o.value);let productActive=-1;
function renderProductResults(){const term=productSearch.value.trim().toLowerCase(),matches=productOptions.filter(o=>!term||(o.textContent+' '+(o.dataset.name||'')).toLowerCase().includes(term));productResults.innerHTML='';productActive=-1;if(!matches.length){productResults.innerHTML='<div class="mfg-product-empty">No matching manufacturable product found.</div>'}else matches.forEach(o=>{const b=document.createElement('button');b.type='button';b.className='mfg-product-option';b.textContent=o.textContent.trim();b.onclick=()=>selectProduct(o);productResults.append(b)});productResults.hidden=false;productSearch.setAttribute('aria-expanded','true')}
function selectProduct(option){product.value=option.value;productSearch.value=option.textContent.trim();productResults.hidden=true;productSearch.setAttribute('aria-expanded','false');product.dispatchEvent(new Event('change'))}
function moveProduct(delta){const buttons=[...productResults.querySelectorAll('.mfg-product-option')];if(!buttons.length)return;productActive=(productActive+delta+buttons.length)%buttons.length;buttons.forEach((b,i)=>b.classList.toggle('active',i===productActive));buttons[productActive].scrollIntoView({block:'nearest'})}
productSearch.addEventListener('focus',renderProductResults);productSearch.addEventListener('input',()=>{product.value='';recipes();renderProductResults()});productSearch.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();moveProduct(1)}else if(e.key==='ArrowUp'){e.preventDefault();moveProduct(-1)}else if(e.key==='Enter'&&productActive>=0){e.preventDefault();productResults.querySelectorAll('.mfg-product-option')[productActive].click()}else if(e.key==='Escape'){productResults.hidden=true;productSearch.setAttribute('aria-expanded','false')}});document.addEventListener('click',e=>{if(!e.target.closest('.mfg-product-search')){productResults.hidden=true;productSearch.setAttribute('aria-expanded','false')}});
const selectedBom=()=>boms.find(b=>b.id==bomSelect.value),money=n=>'Rs '+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
function scaled(){const b=selectedBom(),scale=b&&+qty.value?+qty.value/b.output_quantity:0;return b?b.items.map(i=>({...i,required:i.quantity*scale,total:i.quantity*scale*i.unit_cost})):[]}
function renderMaterials(){const b=selectedBom(),rows=scaled();document.getElementById('recipe-lines').innerHTML=!b?'<p class="rounded-xl bg-amber-50 p-4 text-amber-800">Select a recipe in Step 1.</p>':`<div class="mb-3 rounded-xl bg-purple-50 p-3 text-sm"><b>${b.code}</b> produces ${b.output_quantity} base unit(s). Required quantities below are for ${+qty.value||0} unit(s).</div><table class="serial-table"><thead><tr><th>Raw material</th><th>Recipe qty</th><th>Required qty</th><th>Estimated cost</th></tr></thead><tbody>${rows.map(i=>`<tr><td><b>${i.name}${i.variant?' Â· '+i.variant:''}</b><small class="block">${i.sku}</small></td><td>${i.quantity} ${i.unit}</td><td class="font-bold text-purple-700">${i.required} ${i.unit}</td><td>${money(i.total)}</td></tr>`).join('')}</tbody></table>`}
function go(n){if(n>1&&(!product.value||!bomSelect.value||!document.getElementById('location_id').value||!(+qty.value>0))){alert('Select the product, recipe, warehouse and output quantity first.');return}steps.forEach(s=>{s.classList.toggle('active',+s.dataset.step===n);s.classList.toggle('done',+s.dataset.step<n)});panels.forEach(p=>p.classList.toggle('active',+p.dataset.panel===n));if(n===2)renderMaterials();if(n===3)review()}
function recipes(){const list=boms.filter(b=>b.product_id==product.value);bomSelect.disabled=!list.length;bomSelect.innerHTML=list.length?'<option value="">Select recipe</option>'+list.map(b=>`<option value="${b.id}">${b.code} Â· base output ${b.output_quantity}</option>`).join(''):'<option value="">No active recipe â€” create one first</option>';document.getElementById('bom-help').innerHTML=list.length?`${list.length} active recipe(s) available.`:`This product needs an active recipe. <a class="font-bold text-purple-700 underline" href="{{ route('manufacturing.boms.create') }}">Create recipe</a>`;const o=product.selectedOptions[0],serial=o?.dataset.serial==='1';document.getElementById('selling_price').value=o?.dataset.selling||0;qty.step=serial?'1':'0.0001';document.getElementById('quantity-help').textContent=serial?'One unique serial number will be required for every finished unit.':'';expiry()}
function addExpense(){const n=document.getElementById('expense-template').content.firstElementChild.cloneNode(true),i=expenseIndex++;n.querySelector('.expense-name').name=`expenses[${i}][name]`;n.querySelector('.expense-amount').name=`expenses[${i}][amount]`;n.querySelector('.remove-row').onclick=()=>n.remove();expenses.append(n)}
function review(){const rows=scaled(),material=rows.reduce((s,i)=>s+i.total,0),expense=[...expenses.querySelectorAll('.expense-amount')].reduce((s,e)=>s+(+e.value||0),0),total=material+expense,o=product.selectedOptions[0],b=selectedBom();document.getElementById('review').innerHTML=`<div class="grid gap-3 rounded-xl bg-purple-50 p-4 md:grid-cols-3"><div><small>Finished product</small><b class="block">${o?.dataset.name||''}</b></div><div><small>Recipe</small><b class="block">${b?.code||''}</b></div><div><small>Output</small><b class="block">${+qty.value} ${o?.dataset.unit||''}</b></div></div><table class="serial-table mt-4"><thead><tr><th>Material</th><th>Required</th><th>Cost</th></tr></thead><tbody>${rows.map(i=>`<tr><td>${i.name}</td><td>${i.required} ${i.unit}</td><td>${money(i.total)}</td></tr>`).join('')}</tbody></table><div class="mt-4 rounded-xl bg-slate-900 p-4 text-white"><div class="flex justify-between"><span>Materials</span><b>${money(material)}</b></div><div class="flex justify-between"><span>Expenses</span><b>${money(expense)}</b></div><div class="mt-2 flex justify-between border-t border-white/20 pt-2"><span>Total / estimated unit cost</span><b>${money(total)} / ${money(total/(+qty.value||1))}</b></div></div>`}
function expiry(){const o=product.selectedOptions[0],date=document.getElementById('manufactured_at').value;if(!date||!o?.dataset.expiry)return;const d=new Date(date+'T00:00:00');o.dataset.expiryType==='months'?d.setMonth(d.getMonth()+(+o.dataset.expiry)):d.setDate(d.getDate()+(+o.dataset.expiry));document.getElementById('expires_at').value=d.toISOString().slice(0,10)}
steps.forEach(s=>s.querySelector('button').onclick=()=>go(+s.dataset.step));document.querySelectorAll('.next-step').forEach(b=>b.onclick=()=>go(+b.dataset.next));product.onchange=recipes;bomSelect.onchange=renderMaterials;qty.oninput=renderMaterials;document.getElementById('manufactured_at').onchange=expiry;document.getElementById('add-expense').onclick=addExpense;document.getElementById('mfg-form').onsubmit=()=>document.getElementById('process-button').disabled=true;addExpense()});
</script>@endpush
