@extends('layouts.app')
@section('title', $product->exists ? 'Edit Product' : 'Add Product')
@section('content')
@include('serials.common')
@php
$value=fn($key,$default='')=>old($key,$product->$key ?? $default);
$feature=fn($key,$default=false)=>(bool)($productSettings[$key] ?? $default);
$defaultUnitId=$product->exists?null:($productSettings['default_unit_id']??null);
$sysMargin=$defaultMargin ?? \App\Models\BusinessSetting::current()->default_profit_percent ?? 25;
$selectedLocations=old('location_ids',$product->relationLoaded('locations')?$product->locations->pluck('id')->all():[]);
$sellingInput=$product->exists ? $product->selling_price : '';
if($product->selling_price_tax_type==='inclusive') $sellingInput=round($sellingInput*(1+$product->tax_rate/100),4);
$savedVariants=old('variants',$product->relationLoaded('variants')?$product->variants->map(function($variant) use ($product){return ['value'=>$variant->value,'sku'=>$product->exists?$variant->sku:'','purchase_price'=>$variant->purchase_price,'selling_price'=>$product->selling_price_tax_type==='inclusive'?round($variant->selling_price*(1+$product->tax_rate/100),4):$variant->selling_price];})->values():[]);
$savedComboItems=old('combo_items',$product->relationLoaded('comboItems')?$product->comboItems->map(function($item){return ['product_id'=>$item->id,'quantity'=>$item->pivot->quantity];})->values():[]);
$comboProductOptions=$comboProducts->map(function($item){return ['id'=>$item->id,'name'=>$item->name,'code'=>$item->code,'purchase_price'=>$item->purchase_price,'selling_price'=>$item->selling_price];})->values();
@endphp
<script>window.__defaultMargin = {{ (float) $sysMargin }};</script>
<style>
.product-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:24px}
.product-grid .wide{grid-column:span 2}
.stock-field,.weight-field,.type-field{grid-column:1}
#product-form>.serial-card{padding:26px 24px 30px;margin-bottom:30px;border:1px solid #e8e4f2;border-top:2px solid #a78bfa;box-shadow:0 4px 18px rgb(30 41 59 / 3%);border-radius:16px}
#product-form>.serial-card:nth-of-type(2){border-top-color:#2dd4bf}
#product-form>.serial-card:nth-of-type(3){border-top-color:#a78bfa}
#product-form .product-grid{column-gap:30px;row-gap:20px}
#product-form label{font-size:13px;font-weight:650;color:#263248;margin-bottom:7px}
#product-form input:not([type=checkbox]):not([type=file]),#product-form select{font-size:13px;min-height:40px;padding:9px 12px;border-color:#dce0ee;border-radius:10px;transition:border-color .15s,box-shadow .15s}
#product-form input:focus,#product-form select:focus{outline:none;border-color:#a78bfa;box-shadow:0 0 0 3px #ede9fe}
#product-form input[type=file]{font-size:12px;padding:0;border:1px solid #dce0ee;border-radius:10px;min-height:40px;color:#64748b;overflow:hidden}
#product-form input[type=file]::file-selector-button{border:0;border-right:1px solid #ddd6fe;padding:11px 14px;margin-right:10px;background:#f3edff;color:#7c3aed;font-weight:600;cursor:pointer}
#product-form .product-pricing{table-layout:fixed;border:1px solid #e6e3ef}
#product-form .product-pricing th{background:#7761ac;color:white;font-size:12px;padding:10px;border-right:1px solid #ffffff30;white-space:normal}
#product-form .product-pricing th:first-child{width:38%}
#product-form .product-pricing th:last-child{width:25%}
#product-form .product-pricing td{padding:12px 10px;vertical-align:top;border-right:1px solid #eeeaf5}
#product-form .product-pricing .product-info{background:#ede9fe;color:#6d28d9}
.product-actions{padding-top:6px;gap:0!important}
.product-actions .serial-btn{border-radius:0;padding:12px 20px;box-shadow:0 3px 8px #7c3aed18}
.product-actions .serial-btn:first-child{border-radius:24px 0 0 24px;background:#7561a8}
.product-actions .serial-btn:last-child{border-radius:0 24px 24px 0;background:#0d9488}
.product-help{color:#8490a4;font-size:11px;line-height:1.6;margin-top:6px}
.quick-add{border:1px solid #ddd6fe;border-radius:10px;color:#9333ea;font-size:22px;padding:0 12px;height:44px;align-self:flex-start}
.serial-card input[type=checkbox]{accent-color:#9333ea;width:16px;height:16px;margin-right:6px;vertical-align:middle}
.product-info{position:relative;display:inline-flex;align-items:center;justify-content:center;width:17px;height:17px;margin-left:4px;border-radius:50%;background:#ede9fe;color:#6d28d9;font-size:11px;font-weight:800;line-height:1;cursor:help;vertical-align:middle;box-shadow:0 1px 3px #0001}
.product-info::after{content:none}
.product-tooltip{position:fixed;z-index:10000;width:280px;max-width:calc(100vw - 24px);padding:13px 15px;border:1px solid #b8bec8;border-radius:5px;background:#fff;color:#263248;box-shadow:0 4px 12px rgb(15 23 42 / 25%);font-size:13px;font-weight:400;line-height:1.45;text-align:left;white-space:pre-line;pointer-events:none;opacity:0;visibility:hidden;transform:translateY(4px);transition:opacity .12s,transform .12s,visibility .12s}
.product-tooltip.is-visible{opacity:1;visibility:visible;transform:translateY(0)}
.product-tooltip::before,.product-tooltip::after{content:"";position:absolute;left:var(--arrow-left,50%);transform:translateX(-50%);border-left:8px solid transparent;border-right:8px solid transparent}
.product-tooltip[data-side="bottom"]::before{bottom:100%;border-bottom:9px solid #b8bec8}.product-tooltip[data-side="bottom"]::after{bottom:calc(100% - 1px);border-bottom:9px solid #fff}
.product-tooltip[data-side="top"]::before{top:100%;border-top:9px solid #b8bec8}.product-tooltip[data-side="top"]::after{top:calc(100% - 1px);border-top:9px solid #fff}
#product-description{min-height:190px;padding:14px;outline:none;overflow-wrap:anywhere;font-size:14px}
#product-description ul{list-style:disc;padding-left:20px}#product-description ol{list-style:decimal;padding-left:20px}
#product-description p{margin-bottom:8px}
#reference-dialog{position:fixed;inset:0;margin:auto;border:0;padding:24px;border-radius:16px;width:min(440px,calc(100vw - 24px));max-height:calc(100dvh - 32px);overflow:auto}
#reference-dialog::backdrop{background:#0f172a88;backdrop-filter:blur(3px)}
.type-panel{margin-top:22px;border:1px solid #e6e3ef;border-radius:14px;overflow:hidden;background:#fff}.type-panel-title{padding:12px 16px;background:#f4f0ff;color:#5b3f95;font-weight:700}.dynamic-table th{background:#7761ac!important}.row-remove{width:30px;height:30px;border-radius:50%;background:#f43f5e;color:white;border:0}.row-add{width:32px;height:32px;border-radius:50%;background:#8b5cf6;color:white;font-size:20px;border:0;box-shadow:0 2px 8px #8b5cf655;cursor:pointer;transition:transform .15s,background-color .15s}.row-add:hover{background:#7c3aed;transform:scale(1.08)}
.variation-builder-heading{display:flex;align-items:center;gap:10px;margin:24px 0 10px;font-size:17px;font-weight:700;color:#4c3b7d}.variation-focus{display:grid;place-items:center;width:34px;height:34px;border:0;border-radius:50%;background:#8b5cf6;color:#fff;font-size:21px;line-height:1;box-shadow:0 4px 10px rgb(139 92 246 / 25%)}.variation-builder{display:grid;grid-template-columns:112px minmax(0,1fr);border:1px solid #e6e3ef;border-radius:12px;overflow:hidden}.variation-column-title{padding:10px 12px;background:#55b95c;color:#fff;font-size:13px;font-weight:700}.variation-values-title{background:#55b95c}.variation-selector{background:#fbfaff;border-right:1px solid #e6e3ef}.variation-selector select{margin:10px;width:calc(100% - 20px)}.variation-values{min-width:0;overflow:visible}.variation-values .overflow-x-auto{margin:0;overflow:visible}.variation-values .product-pricing{border:0}.variation-values .product-pricing th{background:#7561a8!important;border-radius:0}.variation-values .product-pricing td{padding:10px 8px}.variation-values .product-pricing tr:last-child td{border-bottom:0}
#variable-pricing .product-pricing{width:100%;min-width:0!important;table-layout:fixed}#variable-pricing .product-pricing th:first-child{width:13%}#variable-pricing .product-pricing th:nth-child(2){width:9%}#variable-pricing .product-pricing th:nth-child(3){width:25%}#variable-pricing .product-pricing th:nth-child(4){width:11%}#variable-pricing .product-pricing th:nth-child(5){width:16%}#variable-pricing .product-pricing th:nth-child(6){width:22%}#variable-pricing .product-pricing th:last-child{width:4%}#variable-pricing .product-pricing th{vertical-align:bottom}#variable-pricing .product-pricing td{padding:6px 5px;vertical-align:middle}#variable-pricing .product-pricing td:last-child{padding-left:3px;padding-right:3px;text-align:center}#variable-pricing .product-pricing input{width:100%;min-width:0}#variable-pricing .product-pricing input[type=file]{max-width:100%}.variant-header-note{display:flex;justify-content:space-between;gap:10px;margin-top:5px;font-size:10px;font-style:italic;font-weight:500}.variant-purchase-fields,.variant-margin-fields{display:flex;align-items:center;gap:6px}.variant-purchase-fields input{flex:1;min-width:0}.variant-margin-fields input{flex:1}.variant-file{display:flex;align-items:center;gap:5px;min-width:0}.variant-file input{font-size:11px!important}.variant-file input::file-selector-button{padding:8px 6px!important;margin-right:5px!important}.variant-file-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:11px;color:#64748b}
.variant-sku-help{position:relative;display:inline-flex;align-items:center;justify-content:center;width:17px;height:17px;margin-left:5px;border-radius:50%;background:#ede9fe;color:#6d28d9;font-size:11px;font-weight:800;cursor:help;vertical-align:middle;box-shadow:0 1px 3px #0001}.variant-sku-help::after{content:attr(data-help);position:absolute;z-index:50;top:calc(100% + 8px);left:-10px;width:240px;padding:10px 14px;border:1px solid #ddd6fe;border-radius:8px;background:#ffffff;color:#334155;box-shadow:0 10px 25px -5px rgba(0,0,0,0.15),0 8px 10px -6px rgba(0,0,0,0.1);white-space:pre-line;line-height:1.5;font-size:12px;font-weight:400;text-align:left;opacity:0;visibility:hidden;pointer-events:none;transition:opacity 0.15s ease-in-out}.variant-sku-help:hover::after,.variant-sku-help:focus-visible::after{opacity:1;visibility:visible}
#combo-pricing .product-pricing th:first-child{width:34%}#combo-pricing .product-pricing th:nth-child(2){width:13%}#combo-pricing .product-pricing th:nth-child(3){width:23%}#combo-pricing .product-pricing th:nth-child(4){width:23%}#combo-pricing .product-pricing th:last-child{width:7%}
.combo-search{position:relative;max-width:620px;margin:0 auto 28px}.combo-search-icon{position:absolute;inset:0 auto 0 0;width:44px;display:grid;place-items:center;color:#64748b;border-right:1px solid #dce0ee;pointer-events:none}.combo-search input{padding-left:58px!important}.combo-results{position:absolute;z-index:20;top:calc(100% + 6px);left:0;right:0;max-height:230px;overflow:auto;background:#fff;border:1px solid #ddd6fe;border-radius:10px;box-shadow:0 14px 28px rgb(30 41 59 / 14%)}.combo-result{display:block;width:100%;padding:10px 14px;text-align:left;color:#263248;border-bottom:1px solid #f1f5f9}.combo-result:hover,.combo-result:focus{background:#f5f3ff;color:#6d28d9}.combo-result small{display:block;color:#64748b;margin-top:2px}.combo-table th{background:#55b95c!important}.combo-table td{vertical-align:middle}.combo-money{font-variant-numeric:tabular-nums;white-space:nowrap}.combo-total-row td{background:#f8fafc;border-top:1px solid #e2e8f0}.combo-total-row strong{color:#263248}.combo-summary{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px;max-width:580px;margin:24px auto 0}.combo-summary label{display:block}
@media(max-width:800px){.product-grid{grid-template-columns:repeat(2,minmax(0,1fr))}#variable-pricing .product-pricing{min-width:760px!important}.variation-builder{grid-template-columns:1fr}.variation-selector{border-right:0;border-bottom:1px solid #e6e3ef}}
@media(max-width:500px){.product-grid{grid-template-columns:minmax(0,1fr)}.product-grid .wide{grid-column:span 1}}
@media(max-width:500px){#product-form>.serial-card{padding:20px 16px}.product-actions{gap:8px!important}.product-actions .serial-btn{border-radius:12px!important;width:100%}}
</style>
<div class="flex flex-wrap justify-between gap-3 mb-6"><h1 class="text-xl font-bold">{{ $product->exists?'Edit product':'Add new product' }}</h1><a class="serial-btn serial-secondary" href="{{ route('products.catalog.index') }}">Products</a></div>
<form id="product-form" method="POST" enctype="multipart/form-data" action="{{ $product->exists?route('products.catalog.update',$product):route('products.catalog.store') }}">@csrf
@if($product->exists) @method('PUT') @endif
<section class="serial-card"><div class="product-grid">
<div><label for="name">Product Name *</label><input id="name" name="name" required maxlength="255" placeholder="Product Name" value="{{ $value('name') }}"></div>
<div><label for="sku">SKU <span class="product-info" tabindex="0" role="button" aria-label="More information" data-help="Enter a unique product code using letters, numbers, dots, hyphens or underscores. Leave empty to generate one automatically.">i</span></label><input id="sku" name="sku" maxlength="100" placeholder="Leave blank to auto-generate" value="{{ old('sku',$product->code) }}"><p class="product-help">Your own code, e.g. PUMP-001, or an automatic PRD-... code.</p></div>
<div><label for="barcode_type">Barcode Type *</label><select name="barcode_type" id="barcode_type">@foreach(['CODE128'=>'Code 128 (C128)','CODE39'=>'Code 39 (C39)','EAN13'=>'EAN-13','UPCA'=>'UPC-A'] as $key=>$label)<option value="{{ $key }}" @selected($value('barcode_type','CODE128')===$key)>{{ $label }}</option>@endforeach</select></div>
<div><label for="unit_id">Unit *</label><div class="flex gap-2"><select required id="unit_id" name="unit_id"><option value="">Please Select</option>@foreach($units as $unit)<option value="{{ $unit->id }}" data-decimal="{{ (int)$unit->allow_decimal }}" @selected($value('unit_id', $defaultUnitId)==$unit->id)>{{ $unit->name }} ({{ $unit->short_name }})</option>@endforeach</select><button type="button" class="quick-add" data-reference="unit" aria-label="Add unit">+</button></div></div>
@if($feature('enable_sub_units'))<div><label for="purchase_unit_id">Purchase / Sub Unit</label><select id="purchase_unit_id" name="purchase_unit_id"><option value="">Same as primary unit</option>@foreach($units as $unit)<option value="{{ $unit->id }}" @selected($value('purchase_unit_id')==$unit->id)>{{ $unit->name }} ({{ $unit->short_name }})</option>@endforeach</select></div>@endif
@if($feature('enable_secondary_unit'))<div><label for="secondary_unit_id">Secondary Unit</label><select id="secondary_unit_id" name="secondary_unit_id"><option value="">No secondary unit</option>@foreach($units as $unit)<option value="{{ $unit->id }}" @selected($value('secondary_unit_id')==$unit->id)>{{ $unit->name }} ({{ $unit->short_name }})</option>@endforeach</select></div>@endif
@if($feature('enable_brands', true))<div><label for="brand_id">Brand</label><div class="flex gap-2"><select id="brand_id" name="brand_id"><option value="">Please Select</option>@foreach($brands as $brand)<option value="{{ $brand->id }}" @selected($value('brand_id')==$brand->id)>{{ $brand->name }}</option>@endforeach</select><button type="button" class="quick-add" data-reference="brand" aria-label="Add brand">+</button></div></div>@endif
@if($feature('enable_warranty'))<div><label for="warranty_id">Warranty</label><select id="warranty_id" name="warranty_id"><option value="">No warranty</option>@foreach($warranties as $warranty)<option value="{{ $warranty->id }}" @selected($value('warranty_id')==$warranty->id)>{{ $warranty->name }} ({{ $warranty->formatted_duration }})</option>@endforeach</select><p class="product-help">Expiry is calculated from the sale date.</p></div>@endif
@if($feature('enable_categories', true))<div><label for="category_id">Category</label><div class="flex gap-2"><select id="category_id" name="category_id"><option value="">Please Select</option>@foreach($categories->whereNull('parent_id') as $category)<option value="{{ $category->id }}" @selected($value('category_id')==$category->id)>{{ $category->name }}</option>@endforeach</select></div></div>@endif
@if($feature('enable_categories', true) && $feature('enable_subcategories', true))@include('products.partials.subcategory-picker')@endif
@include('products.partials.location-picker')
<div class="stock-field"><input type="hidden" name="manage_stock" value="0"><label class="flex items-center gap-2" for="manage_stock"><input type="checkbox" id="manage_stock" name="manage_stock" value="1" @checked($value('manage_stock',true))> Manage Stock? <span class="product-info" tabindex="0" role="button" aria-label="Manage stock information" data-help="Enable or disable stock management for a product.&#10;&#10;Stock Management should be disabled mostly for services. Example: Hair-Cutting, Repairing, etc.">i</span></label><p class="product-help">Enable stock management at product level.</p></div>
<div><label for="alert_quantity">Alert quantity <span class="product-info" tabindex="0" role="button" aria-label="Alert quantity information" data-help="Get alert when product stock reaches or goes below the specified quantity.&#10;&#10;Products with low stock will be displayed in dashboard - Product Stock Alert section.">i</span></label><input type="number" min="0" max="999999999" step="0.0001" name="alert_quantity" id="alert_quantity" value="{{ $value('alert_quantity') }}" placeholder="Alert quantity"></div>
<div></div>
<div class="wide"><label for="description">Product Description</label><textarea name="description" id="description" rows="10" class="w-full border border-slate-300 rounded-xl p-3">{{ \App\Services\ProductDescription::clean($value('description')) }}</textarea></div>
<div><label for="image">Product image</label><input type="file" id="image" name="image" accept=".jpg,.jpeg,.png,.webp"><p class="product-help">Max 5 MB. Square images work best.</p>@if($product->image_path)<img class="mt-3 rounded-xl max-h-36" alt="Current product image" src="{{ route('products.catalog.attachment',[$product,'image']) }}">@endif<img id="image-preview" class="hidden mt-3 rounded-xl max-h-36" alt="Selected product image"></div>
<div class="wide"><label for="brochure">Product brochure</label><input type="file" id="brochure" name="brochure" accept=".pdf,.csv,.txt,.zip,.doc,.docx,.jpeg,.jpg,.png"><p class="product-help">Max 5 MB. PDF, CSV, TXT, ZIP, DOC, DOCX, JPG or PNG.</p>@if($product->brochure_path)<a class="text-sm text-purple-700" href="{{ route('products.catalog.attachment',[$product,'brochure']) }}">Download current brochure</a>@endif</div>
</div></section>
<section class="serial-card"><div class="product-grid">
<div><input type="hidden" name="enable_serial" value="0"><label for="enable_serial"><input type="checkbox" id="enable_serial" name="enable_serial" value="1" @checked($value('enable_serial',false))> Enable Product description, IMEI or Serial Number <span class="product-info" tabindex="0" role="button" aria-label="More information" data-help="Enable or disable adding product description, IMEI or Serial number while selling products in POS screen.">i</span></label><p class="product-help">Requires stock management and a whole-number unit.</p></div>
<div><input type="hidden" name="is_raw_material" value="0"><label for="is_raw_material"><input type="checkbox" id="is_raw_material" name="is_raw_material" value="1" @checked($value('is_raw_material',false))> Is Raw Material</label><p class="product-help">Makes this product available as a manufacturing component.</p></div>
<div><input type="hidden" name="not_for_selling" value="0"><label for="not_for_selling"><input type="checkbox" id="not_for_selling" name="not_for_selling" value="1" @checked($value('not_for_selling',false))> Not for selling <span class="product-info" tabindex="0" role="button" aria-label="More information" data-help="If checked, product will not be displayed in sales screen for selling purposes.">i</span></label></div>
<div class="wide rounded-xl border border-purple-100 bg-purple-50 p-3 text-sm text-purple-800"><b>Manufacturing and lot setup is automatic.</b><span class="block text-xs">A stock-managed Single product is available as a finished product. When â€œIs Raw Materialâ€ is selected, it is available only in recipe materials. Finished production lots are generated automatically.</span></div>
<div class="weight-field"><label for="weight">Weight</label><input id="weight" name="weight" maxlength="100" value="{{ $value('weight') }}" placeholder="e.g. 2 kg"></div>
@if($feature('expiry_enabled'))<div><label for="expiry_period">Product Expiry</label><div class="flex gap-2"><input id="expiry_period" name="expiry_period" type="number" min="1" max="1200" value="{{ $value('expiry_period') }}" placeholder="Period"><select id="expiry_period_type" name="expiry_period_type"><option value="">Select period</option><option value="days" @selected($value('expiry_period_type')==='days')>Days</option><option value="months" @selected($value('expiry_period_type')==='months')>Months</option></select></div><p class="product-help">Leave empty for products without an expiry period.</p></div>@endif
</div><div class="serial-grid mt-6">@for($i=0;$i<4;$i++)<div><label for="custom-{{ $i }}">Custom Field {{ $i+1 }}</label><input id="custom-{{ $i }}" name="custom_fields[{{ $i }}]" maxlength="255" value="{{ old('custom_fields.'.$i,$product->custom_fields[$i]??'') }}"></div>@endfor</div></section>
<section class="serial-card"><div class="product-grid">
<div><label for="tax_mode">Applicable Tax</label><select id="tax_mode"><option value="none" @selected(!$value('tax_rate_id') && (float)$value('tax_rate',0)===0)>None</option>@foreach($taxRates as $configuredTax)<option value="tax:{{ $configuredTax->id }}" data-rate="{{ $configuredTax->amount }}" @selected((int)$value('tax_rate_id')===$configuredTax->id)>{{ $configuredTax->name }} â€” {{ number_format((float)$configuredTax->amount,3) }}%{{ $configuredTax->is_tax_group?' (Group)':'' }}</option>@endforeach<option value="custom" @selected(!$value('tax_rate_id') && (float)$value('tax_rate',0)>0)>Custom rate (%)</option></select><input type="hidden" name="tax_rate_id" id="tax_rate_id" value="{{ $value('tax_rate_id') }}"><input aria-label="Tax rate percentage" class="mt-2" type="number" name="tax_rate" id="tax_rate" min="0" max="100" step="0.001" required value="{{ $value('tax_rate',0) }}"><p class="product-help">Configured tax rates are maintained in Settings â†’ Tax Rates.</p></div>
<div><label for="selling_price_tax_type">Selling Price Tax Type *</label><select name="selling_price_tax_type" id="selling_price_tax_type"><option value="exclusive" @selected($value('selling_price_tax_type','exclusive')==='exclusive')>Exclusive</option><option value="inclusive" @selected($value('selling_price_tax_type')==='inclusive')>Inclusive</option></select></div>
<div class="type-field"><label for="product_type">Product Type * <span class="product-info" tabindex="0" role="button" aria-label="Product type information" data-help="Single product: Product with no variations.&#10;&#10;Variable product: Product with variations such as size, color etc.&#10;&#10;Combo product: A combination of multiple products, also called bundle product.">i</span></label><select name="product_type" id="product_type">@foreach(['single'=>'Single','variable'=>'Variable','combo'=>'Combo'] as $key=>$label)<option value="{{ $key }}" @selected($value('product_type','single')===$key)>{{ $label }}</option>@endforeach</select><p class="product-help">Variable creates prices for variation values. Combo creates a bundle from existing products.</p></div>
</div><div id="single-pricing">
<div class="overflow-x-auto mt-6"><table class="serial-table product-pricing" style="min-width:730px"><thead><tr><th colspan="2">Default Purchase Price</th><th>Margin (%) <span class="product-info" tabindex="0" role="button" aria-label="More information" data-help="Markup on purchase price excluding tax. Editing the selling price recalculates the margin.">i</span></th><th>Default Selling Price</th><th>Product image</th></tr></thead><tbody><tr>
<td><label for="purchase_price">Exc. tax *</label><input type="number" min="0" max="999999999" step="0.0001" required name="purchase_price" id="purchase_price" value="{{ $value('purchase_price') }}" placeholder="Purchase price"></td>
<td><label for="purchase_price_inc">Inc. tax</label><input type="number" min="0" step="0.0001" id="purchase_price_inc" value="{{ $value('purchase_price_inc') }}" placeholder="Purchase price incl. tax"></td>
<td><label for="margin">Margin</label><input type="number" min="-100" max="999999" step="any" name="margin" id="margin" value="{{ $value('margin',$sysMargin) }}"></td>
<td><label id="selling-label" for="selling_price">Exc. tax *</label><input type="number" min="0" max="999999999" step="0.0001" required name="selling_price" id="selling_price" value="{{ old('selling_price',$sellingInput) }}" placeholder="Selling price"></td>
<td><label for="variant_image">Product image</label><input type="file" name="variant_image" id="variant_image" accept=".jpg,.jpeg,.png,.webp"><p class="product-help">Max 5 MB; square image.</p>@if($product->variant_image_path)<a href="{{ route('products.catalog.attachment',[$product,'variant_image']) }}" class="text-purple-700">Current image</a>@endif</td>
</tr></tbody></table></div><div class="max-w-sm mt-6"><label for="our_price">Our Price</label><input type="number" min="0" max="999999999" step="0.0001" name="our_price" id="our_price" placeholder="Our Price" value="{{ $value('our_price') }}"></div></div>
<div id="variable-pricing" hidden><div class="variation-builder-heading">Add Variation:<span class="text-rose-500">*</span></div><div class="variation-builder"><div class="variation-selector"><div class="variation-column-title">Variation</div><select id="variation_template_id" name="variation_template_id"><option value="">Please Select</option>@foreach($variationTemplates as $template)<option value="{{ $template->id }}" data-values='@json($template->values)' @selected(old('variation_template_id',$product->variants->first()?->variation_template_id)==$template->id)>{{ $template->name }}</option>@endforeach</select></div><div class="variation-values"><div class="variation-column-title variation-values-title">Variation Values</div><div class="overflow-x-auto"><table class="serial-table product-pricing dynamic-table"><thead><tr><th>SKU <span class="variant-sku-help" tabindex="0" role="note" aria-label="SKU is optional. Keep it blank to automatically generate SKU." data-help="SKU is optional.&#10;&#10;Keep it blank to automatically generate SKU.">i</span></th><th>Value</th><th>Default Purchase Price<div class="variant-header-note"><span>Exc. tax</span><span>Inc. tax</span></div></th><th>Ã— Margin(%)</th><th>Default Selling Price<div class="variant-header-note"><span id="variant-selling-tax-label">Exc. Tax</span></div></th><th>Variation Images</th><th><button type="button" id="add-variant-row" class="row-add" aria-label="Add variation value">+</button></th></tr></thead><tbody id="variant-rows"></tbody></table></div></div></div></div>
<div id="combo-pricing" class="type-panel" hidden><div class="type-panel-title">Combo products</div><div class="p-4"><p class="product-help mb-4">Search and add the products included in this bundle. The purchase total and selling price update automatically.</p><div class="combo-search"><i class="bi bi-search combo-search-icon" aria-hidden="true"></i><input id="combo-product-search" type="search" autocomplete="off" placeholder="Enter product name / SKU / Scan bar code" aria-label="Search products for this combo"><div id="combo-search-results" class="combo-results" hidden role="listbox" aria-label="Matching products"></div></div><div class="overflow-x-auto"><table class="serial-table product-pricing dynamic-table combo-table" style="min-width:760px"><thead><tr><th>Product Name</th><th>Quantity</th><th>Purchase Price (Excluding Tax)</th><th>Total Amount (Exc. Tax)</th><th><span class="sr-only">Remove</span><i class="bi bi-trash-fill" aria-hidden="true"></i></th></tr></thead><tbody id="combo-rows"></tbody><tfoot><tr class="combo-total-row"><td></td><td colspan="2" class="text-right"><strong>Net Total Amount :</strong></td><td class="combo-money" id="combo-net-total">Rs 0.00</td><td></td></tr></tfoot></table></div><div class="combo-summary"><div><label for="combo_margin">Ã— Margin(%)</label><input id="combo_margin" type="number" min="-100" max="999999" step="any" value="{{ $value('margin',$sysMargin) }}"></div><div><label for="combo_selling_price">Default Selling Price</label><input id="combo_selling_price" type="number" min="0" max="999999999" step="0.0001" value="{{ old('selling_price',$sellingInput) }}"></div></div></div></div>
</section>
<div class="product-actions flex flex-wrap justify-center gap-3 mb-8"><button class="serial-btn" style="background:#0f766e" name="save_action" value="prices">Save & Add Group Prices</button><button id="save-and-open-stock" class="serial-btn" name="save_action" value="opening">Save &amp; Add Opening Stock</button><button class="serial-btn" style="background:#db2777" name="save_action" value="another">Save And Add Another</button><button class="serial-btn" name="save_action" value="save">Save</button></div>
</form>
<div id="product-tooltip" class="product-tooltip" role="tooltip" aria-hidden="true"></div>
<dialog id="reference-dialog" aria-labelledby="reference-title"><form id="reference-form" class="serial-card" style="padding:0;border:0;margin:0">
<h2 id="reference-title">Add reference</h2><p id="reference-error" role="alert" class="text-rose-600 mb-3"></p>
<label for="reference-name">Name *</label><input id="reference-name" name="name" required maxlength="100">
<div data-ref-kind="unit" class="mt-4"><label for="reference-short">Short name *</label><input id="reference-short" name="short_name" maxlength="30"><label class="mt-4" for="reference-decimal">Allow decimal *</label><select id="reference-decimal" name="allow_decimal"><option value="0">No</option><option value="1">Yes</option></select></div>
<div data-ref-kind="location" class="mt-4"><label for="reference-code">Location code *</label><input id="reference-code" name="code" maxlength="100"></div>
<div class="flex justify-end gap-3 mt-6"><button type="button" class="serial-btn serial-secondary" id="reference-close">Close</button><button id="reference-save" class="serial-btn">Save</button></div>
</form></dialog>
<script type="application/json" id="saved-variants">@json($savedVariants)</script>
<script type="application/json" id="saved-combo-items">@json($savedComboItems)</script>
@endsection
@push('scripts')
@include('products.form-script')
@endpush
