@extends('layouts.app')
@section('title', 'Products')
@section('content')
@include('serials.common')
<style>
.catalog-card{background:#fff;border:1px solid #eee7ff;border-top:2px solid #8b5cf6;border-radius:16px;box-shadow:0 10px 25px rgba(71,45,115,.05)}
.catalog-filter{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px 24px}.catalog-filter label{display:block;margin-bottom:7px;color:#334155;font-size:12px;font-weight:700}.catalog-filter select{width:100%;border:1px solid #d8ddea;border-radius:11px;background:#fff;padding:10px 12px;font-size:13px}
.catalog-tab{border-bottom:3px solid transparent;padding:15px 17px;color:#64748b;font-size:15px;font-weight:700}.catalog-tab.active{border-color:#7c3aed;color:#6d28d9;background:#faf8ff}.product-thumb{display:grid;width:48px;height:48px;place-items:center;overflow:hidden;border-radius:10px;background:#f1f5f9;color:#94a3b8}.product-thumb img{width:100%;height:100%;object-fit:cover}
.action-menu{position:fixed;z-index:60;width:210px;overflow:hidden;border:1px solid #e2e8f0;border-radius:12px;background:#fff;box-shadow:0 16px 35px rgba(15,23,42,.16)}.action-menu a,.action-menu button{display:flex;width:100%;align-items:center;gap:9px;padding:9px 13px;color:#475569;font-size:12px;text-align:left}.action-menu a:hover,.action-menu button:hover{background:#f5f3ff;color:#6d28d9}.dataTables_wrapper .dt-buttons{float:none;display:inline-flex;margin:0 0 15px}.dataTables_wrapper .dataTables_filter{margin-bottom:15px}
.product-table-host .dataTables_info,.product-table-host .dataTables_paginate{margin-top:12px}
@media(max-width:900px){.catalog-filter{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:520px){.catalog-filter{grid-template-columns:1fr}}
</style>

<div class="mb-6 flex flex-wrap items-end justify-between gap-3"><div class="flex items-baseline gap-3"><h1 class="text-2xl font-extrabold text-slate-900">Products</h1><span class="text-sm text-slate-500">Manage your products</span></div><a href="{{ route('products.catalog.create') }}" class="serial-btn"><i class="bi bi-plus-lg mr-1"></i>Add Product</a></div>

<section class="catalog-card mb-7 overflow-hidden">
 <div class="border-b border-slate-200 px-6 py-4"><h2 class="m-0 flex items-center gap-2 text-base font-bold text-purple-700"><i class="bi bi-funnel-fill"></i>Filters</h2></div>
 <form method="GET" class="p-6" data-auto-filter><div class="catalog-filter">
  <div><label for="product_type">Product Type</label><select id="product_type" name="product_type"><option value="">All</option>@foreach(['single'=>'Single','variable'=>'Variable','combo'=>'Combo'] as $key=>$label)<option value="{{ $key }}" @selected(request('product_type') === $key)>{{ $label }}</option>@endforeach</select></div>
  <div><label for="category_id">Category</label><select id="category_id" name="category_id"><option value="">All</option>@foreach($categories->whereNull('parent_id') as $category)<option value="{{ $category->id }}" @selected((string)request('category_id') === (string)$category->id)>{{ $category->name }}</option>@endforeach</select></div>
  <div><label for="unit_id">Unit</label><select id="unit_id" name="unit_id"><option value="">All</option>@foreach($units as $unit)<option value="{{ $unit->id }}" @selected((string)request('unit_id') === (string)$unit->id)>{{ $unit->name }}</option>@endforeach</select></div>
  <div><label for="tax_rate">Tax</label><select id="tax_rate" name="tax_rate"><option value="">All</option>@foreach($products->pluck('tax_rate')->unique()->sort() as $tax)<option value="{{ $tax }}" @selected((string)request('tax_rate') === (string)$tax)>{{ number_format($tax,3) }}%</option>@endforeach</select></div>
  <div><label for="brand_id">Brand</label><select id="brand_id" name="brand_id"><option value="">All</option>@foreach($brands as $brand)<option value="{{ $brand->id }}" @selected((string)request('brand_id') === (string)$brand->id)>{{ $brand->name }}</option>@endforeach</select></div>
  <div><label for="location_id">Business Location</label><select id="location_id" name="location_id"><option value="">All</option>@foreach($locations as $location)<option value="{{ $location->id }}" @selected((string)request('location_id') === (string)$location->id)>{{ $location->name }}</option>@endforeach</select></div>
  <div><label for="stock_status">Stock Management</label><select id="stock_status" name="stock_status"><option value="">All</option><option value="managed" @selected(request('stock_status') === 'managed')>Managed stock</option><option value="unmanaged" @selected(request('stock_status') === 'unmanaged')>Not managed</option><option value="serial" @selected(request('stock_status') === 'serial')>Serial tracked</option></select></div>
  <label class="flex cursor-pointer items-center gap-3 self-end pb-2"><input type="checkbox" name="not_for_selling" value="1" class="h-5 w-5 rounded border-slate-300 text-purple-600" @checked(request()->boolean('not_for_selling'))><span class="text-sm font-bold text-slate-700">Not for selling</span></label>
 </div>@if(request()->query())<div class="mt-5 flex justify-end"><a href="{{ route('products.catalog.index') }}" class="serial-btn serial-secondary">Reset filters</a></div>@endif</form>
</section>

<section class="catalog-card overflow-visible">
 <div class="flex border-b border-slate-200" role="tablist"><button type="button" class="catalog-tab active" data-panel="products-panel" role="tab" aria-selected="true"><i class="bi bi-boxes mr-2"></i>All Products</button><button type="button" class="catalog-tab" data-panel="stock-panel" role="tab" aria-selected="false"><i class="bi bi-hourglass-split mr-2"></i>Stock Report</button></div>
 <div id="products-panel" class="p-5" role="tabpanel"><div class="mb-4 flex justify-end"><button type="button" id="download-products" class="serial-btn"><i class="bi bi-file-earmark-excel-fill mr-1"></i>Download Excel</button></div><div class="product-table-host"><table id="products-table" class="display nowrap w-full"><thead><tr><th><input id="select-all-products" type="checkbox" aria-label="Select all products"></th><th>Image</th><th>Action</th><th>Product</th><th>Business Location</th><th>Unit Purchase Price</th><th>Selling Price</th><th>Current Stock</th><th>Product Type</th><th>Category</th><th>Brand</th><th>Tax</th><th>SKU</th><th>Custom Field 1</th><th>Custom Field 2</th><th>Custom Field 3</th><th>Custom Field 4</th></tr></thead><tbody>
 @foreach($products as $product)
  @php $stock=$product->enable_serial?$product->locations->sum(fn($location)=>(int)($serialStock->get($product->id.':'.$location->id)?->quantity??0)):$product->locations->sum(fn($location)=>(float)$location->pivot->opening_quantity); @endphp
  <tr><td><input class="product-select" type="checkbox" value="{{ $product->id }}" aria-label="Select {{ $product->name }}"></td><td>@if($product->image_path)<a class="product-thumb" href="{{ route('products.catalog.attachment',[$product,'image']) }}" target="_blank"><img src="{{ route('products.catalog.attachment',[$product,'image']) }}" alt=""></a>@else<span class="product-thumb"><i class="bi bi-image"></i></span>@endif</td>
  <td><div class="relative inline-block"><button type="button" class="action-toggle rounded-full bg-purple-600 px-3 py-1.5 text-xs font-bold text-white">Actions <i class="bi bi-chevron-down"></i></button><div class="action-menu hidden"><button type="button" class="view-product" data-product-id="{{ $product->id }}"><i class="bi bi-eye"></i>View</button><a href="{{ route('products.catalog.edit',$product) }}"><i class="bi bi-pencil-square"></i>Edit</a>@if($product->manage_stock)<a href="{{ route('products.catalog.opening',$product) }}"><i class="bi bi-database-add"></i>Add or edit opening stock</a>@endif @if($product->enable_serial)<a href="{{ route('products.serials.index',['product_id'=>$product->id]) }}"><i class="bi bi-upc-scan"></i>Serial numbers</a>@endif<form method="POST" action="{{ route('products.catalog.destroy',$product) }}" onsubmit="return confirm('Delete this product? This action cannot be undone.')">@csrf @method('DELETE')<button type="submit" class="text-rose-600"><i class="bi bi-trash"></i>Delete</button></form></div></div></td>
  <td class="font-semibold text-slate-800">{{ $product->name }}@if($product->not_for_selling)<span class="ml-2 rounded-full bg-amber-100 px-2 py-0.5 text-[10px] text-amber-700">Not for selling</span>@endif</td><td>{{ $product->locations->pluck('name')->implode(', ') ?: '—' }}</td><td>Rs {{ number_format($product->purchase_price,2) }}</td><td>Rs {{ number_format($product->selling_price,2) }}</td><td><span class="font-bold {{ $product->alert_quantity!==null&&$stock<=$product->alert_quantity?'text-rose-600':'text-emerald-700' }}">{{ number_format($stock,$product->unit?->allow_decimal?2:0) }} {{ $product->unit?->short_name }}</span></td><td>{{ ucfirst($product->product_type) }}</td><td>{{ $product->category?->name ?? '—' }}</td><td>{{ $product->brand?->name ?? '—' }}</td><td>{{ number_format($product->tax_rate,3) }}%</td><td>{{ $product->code }}</td>@for($field=0;$field<4;$field++)<td>{{ $product->custom_fields[$field] ?? '' }}</td>@endfor</tr>
 @endforeach
 </tbody></table></div></div>
 <div id="stock-panel" class="hidden p-5" role="tabpanel"><div class="product-table-host"><table id="stock-table" class="display nowrap w-full"><thead><tr><th>SKU</th><th>Product</th><th>Variation</th><th>Category</th><th>Location</th><th>Unit Selling Price</th><th>Current Stock</th><th>Current Stock Value (By purchase price)</th><th>Current Stock Value (By sale price)</th><th>Potential Profit</th><th>Total Unit Sold</th><th>Total Unit Transferred</th><th>Total Unit Adjusted</th><th>Custom Field 1</th><th>Custom Field 2</th><th>Custom Field 3</th><th>Custom Field 4</th></tr></thead><tbody>
 @foreach($stockRows as $row)@php($product=$row['product'])<tr class="{{ $row['stock'] < 0 ? 'bg-rose-50' : '' }}"><td>{{ $product->code }}</td><td>{{ $product->name }}</td><td>{{ $row['variation'] }}</td><td>{{ $product->category?->name ?? '' }}</td><td>{{ $row['location']->name }}</td><td>Rs {{ number_format($product->selling_price,2) }}</td><td>{{ number_format($row['stock'],$product->unit?->allow_decimal?2:0) }} {{ $product->unit?->short_name }}</td><td>Rs {{ number_format($row['purchase_value'],2) }}</td><td>Rs {{ number_format($row['sale_value'],2) }}</td><td>Rs {{ number_format($row['potential_profit'],2) }}</td><td>{{ number_format($row['sold'],2) }} {{ $product->unit?->short_name }}</td><td>{{ number_format($row['transferred'],2) }} {{ $product->unit?->short_name }}</td><td>{{ number_format($row['adjusted'],2) }} {{ $product->unit?->short_name }}</td>@for($field=0;$field<4;$field++)<td>{{ $product->custom_fields[$field] ?? '' }}</td>@endfor</tr>@endforeach
 </tbody><tfoot><tr class="bg-slate-200 font-extrabold"><th colspan="6" class="text-right">Total:</th><th>{{ number_format($stockTotals['stock'],2) }}</th><th>Rs {{ number_format($stockTotals['purchase_value'],2) }}</th><th>Rs {{ number_format($stockTotals['sale_value'],2) }}</th><th>Rs {{ number_format($stockTotals['potential_profit'],2) }}</th><th>{{ number_format($stockTotals['sold'],2) }}</th><th>{{ number_format($stockTotals['transferred'],2) }}</th><th>{{ number_format($stockTotals['adjusted'],2) }}</th><th colspan="4"></th></tr></tfoot></table></div></div>
</section>

<div id="product-modal" class="fixed inset-0 z-50 hidden items-center justify-center bg-slate-950/55 p-4" role="dialog" aria-modal="true" aria-labelledby="product-modal-title"><div class="w-full max-w-2xl overflow-hidden rounded-2xl bg-white shadow-2xl"><div class="flex items-center justify-between border-b border-purple-100 bg-purple-50 px-6 py-4"><h2 id="product-modal-title" class="text-lg font-bold">Product details</h2><button type="button" class="close-product-modal text-2xl text-slate-400" aria-label="Close">&times;</button></div><div id="product-modal-body" class="grid gap-4 p-6 sm:grid-cols-2"></div><div class="flex justify-end border-t border-slate-200 px-6 py-4"><button type="button" class="close-product-modal serial-btn serial-secondary">Close</button></div></div></div>
@endsection

@push('scripts')
<script>
$(function(){
 const productDetails=@json($productDetails);
 const makeButtons=columns=>[{extend:'csvHtml5',text:'<i class="bi bi-filetype-csv"></i> Export to CSV',exportOptions:{columns}},{extend:'excelHtml5',text:'<i class="bi bi-file-earmark-excel"></i> Export to Excel',exportOptions:{columns}},{extend:'print',text:'<i class="bi bi-printer"></i> Print',exportOptions:{columns}},{extend:'colvis',text:'<i class="bi bi-layout-three-columns"></i> Column visibility'},{extend:'pdfHtml5',text:'<i class="bi bi-file-earmark-pdf"></i> Export to PDF',orientation:'landscape',exportOptions:{columns}}];
 const productsTable=$('#products-table').DataTable({dom:'Bfrtip',buttons:makeButtons([3,4,5,6,7,8,9,10,11,12,13,14,15,16]),pageLength:25,order:[[3,'asc']],columnDefs:[{orderable:false,targets:[0,1,2]}],autoWidth:false});const stockTable=$('#stock-table').DataTable({dom:'Bfrtip',buttons:makeButtons([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]),pageLength:25,order:[[0,'asc'],[2,'asc']],autoWidth:false});
 StickyDataTables.install(productsTable);StickyDataTables.install(stockTable);
 $('.sticky-table-viewport').on('scroll',()=>$('.action-menu').addClass('hidden'));
 $('#download-products').on('click',()=>productsTable.button('.buttons-excel').trigger());$('.catalog-tab').on('click',function(){$('.catalog-tab').removeClass('active').attr('aria-selected','false');$(this).addClass('active').attr('aria-selected','true');$('[role="tabpanel"]').addClass('hidden');$('#'+this.dataset.panel).removeClass('hidden');if(this.dataset.panel==='stock-panel')stockTable.columns.adjust();requestAnimationFrame(StickyDataTables.update)});
 $(document).on('click','.action-toggle',function(event){event.stopPropagation();const button=$(this),menu=button.data('actionMenu')||button.next('.action-menu');button.data('actionMenu',menu);$('.action-menu').not(menu).addClass('hidden');if(!menu.parent().is('body'))menu.appendTo(document.body);const opening=menu.hasClass('hidden');if(opening){const rect=this.getBoundingClientRect(),width=menu.outerWidth()||210;menu.css({top:(rect.bottom+6)+'px',left:Math.max(8,Math.min(rect.right-width,window.innerWidth-width-8))+'px'});}menu.toggleClass('hidden',!opening)}).on('click',()=>$('.action-menu').addClass('hidden'));
 $(window).on('scroll resize',()=>$('.action-menu').addClass('hidden'));
 $('#select-all-products').on('change',function(){$('.product-select').prop('checked',this.checked)});
 $('.view-product').on('click',function(){const product=productDetails[this.dataset.productId];const labels={name:'Product',sku:'SKU',unit:'Unit',brand:'Brand',category:'Category',locations:'Business locations',purchase_price:'Purchase price',selling_price:'Selling price',serial_tracking:'Serial tracking'};$('#product-modal-body').html(Object.values(labels).map(label=>`<div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">${label}</p><p class="mt-1 text-sm font-semibold text-slate-800"></p></div>`).join(''));$('#product-modal-body>div').each(function(index){$(this).find('p:last').text(product[Object.keys(labels)[index]])});$('#product-modal').removeClass('hidden').addClass('flex')});$('.close-product-modal').on('click',()=>$('#product-modal').addClass('hidden').removeClass('flex'));
});
</script>
@endpush
