@extends('layouts.app')
@section('title','Payment Accounts')
@section('content')
<div class="mb-5 flex items-baseline gap-3"><h1 class="text-xl font-bold">Payment Accounts</h1><span class="text-sm text-slate-500">Manage your payment accounts</span></div>
@if(session('status'))<div class="mb-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{{ session('status') }}</div>@endif
@if(session('error')||$errors->any())<div class="mb-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{{ session('error') ?: $errors->first() }}</div>@endif
<section class="overflow-hidden rounded-2xl border border-purple-100 bg-white shadow-sm">
<div class="flex border-b border-purple-100 px-4"><button class="tab border-b-2 border-purple-600 px-4 py-4 text-sm font-bold text-purple-700" data-panel="accounts"><i class="bi bi-credit-card-2-front-fill"></i> Accounts</button><button class="tab border-b-2 border-transparent px-4 py-4 text-sm font-bold text-slate-500" data-panel="types"><i class="bi bi-list-ul"></i> Account Types</button></div>
<div id="accounts" class="p-4 sm:p-6"><div class="mb-4 rounded-xl bg-rose-500 px-5 py-4 text-sm font-semibold text-white"><i class="bi bi-exclamation-circle-fill"></i> Total 0 payments not linked with any account. <button class="underline">View Details</button></div><div class="mb-5 flex items-center justify-between rounded-2xl border border-purple-100 bg-purple-50/40 p-4"><select id="account-state" class="rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm"><option value="active">Active</option><option value="closed">Closed</option><option value="all">All accounts</option></select><button id="add-account" class="rounded-xl bg-purple-600 px-4 py-2 text-xs font-bold text-white"><i class="bi bi-plus-lg"></i> Add</button></div><div class="mb-4 flex justify-end"><input id="account-search" placeholder="Search ..." class="rounded-xl border border-slate-300 px-3 py-2 text-sm"></div><table class="w-full text-left text-sm"><thead class="bg-slate-50"><tr><th class="p-3">Name</th><th>Account Type</th><th>Account Sub Type</th><th>Account Number</th><th>Balance</th><th>Account details</th><th>Action</th></tr></thead><tbody>@foreach($accounts as $a)<tr class="account-row border-t" data-state="{{ $a->is_active?'active':'closed' }}"><td class="p-3 font-semibold">{{ $a->name }}</td><td>{{ $a->type?->name ?? '—' }}</td><td>{{ $a->subType?->name ?? '—' }}</td><td>{{ $a->account_number }}</td><td>Rs. {{ number_format($a->current_balance,2) }}</td><td class="text-xs">@foreach($a->details as $d)<p><b>{{ $d->label }}:</b> {{ $d->value }}</p>@endforeach</td><td class="space-y-1"><button class="edit-account rounded bg-cyan-500 px-2 py-1 text-xs font-bold text-white" data-a='@json($a)' data-url="{{ route('payment-accounts.update',$a) }}">Edit</button><a href="{{ route('payment-accounts.book',$a) }}" class="rounded bg-amber-500 px-2 py-1 text-xs font-bold text-white">Account Book</a><button data-account-id="{{ $a->id }}" class="fund-transfer rounded bg-cyan-500 px-2 py-1 text-xs font-bold text-white">Fund Transfer</button><button data-account-id="{{ $a->id }}" class="deposit-account rounded bg-emerald-500 px-2 py-1 text-xs font-bold text-white">Deposit</button><button data-url="{{ route('payment-accounts.close',$a) }}" data-name="{{ $a->name }}" class="close-account rounded bg-rose-500 px-2 py-1 text-xs font-bold text-white">Close</button></td></tr>@endforeach</tbody><tfoot class="bg-slate-200 font-bold"><tr><td class="p-3 text-right" colspan="4">Total:</td><td>Rs. {{ number_format($accounts->sum('current_balance'),2) }}</td><td colspan="2"></td></tr></tfoot></table></div>
<div id="types" class="hidden p-4 sm:p-6"><div class="mb-4 rounded-xl bg-rose-500 px-5 py-4 text-sm font-semibold text-white"><i class="bi bi-exclamation-circle-fill"></i> Total 0 payments not linked with any account. <button class="underline">View Details</button></div><div class="mb-5 flex justify-end"><button id="add-type" class="rounded-xl bg-purple-600 px-4 py-2 text-xs font-bold text-white"><i class="bi bi-plus-lg"></i> Add</button></div><table class="w-full text-left text-sm"><thead class="bg-slate-50"><tr><th class="p-3">Name</th><th>Parent account type</th><th>Action</th></tr></thead><tbody>@foreach($types as $t)<tr class="border-t"><td class="p-3 font-semibold">{{ $t->name }}</td><td>—</td><td><button class="edit-type rounded bg-purple-50 px-2 py-1 text-xs font-bold text-purple-700" data-t='@json($t)'>Edit</button></td></tr>@foreach($t->children as $child)<tr class="border-t"><td class="p-3 pl-8"><i class="bi bi-arrow-return-right text-purple-500"></i> {{ $child->name }}</td><td>{{ $t->name }}</td><td><button class="edit-type rounded bg-purple-50 px-2 py-1 text-xs font-bold text-purple-700" data-t='@json($child)'>Edit</button></td></tr>@endforeach @endforeach</tbody></table></div>
</section>
<dialog id="account-modal" class="w-[calc(100%-2rem)] max-w-2xl rounded-2xl border-0 p-0 shadow-2xl"><form id="account-form" method="POST" action="{{ route('payment-accounts.store') }}">@csrf<input name="_method" value="POST" type="hidden"><header class="flex justify-between border-b bg-purple-50 px-5 py-4 font-bold text-purple-900"><span id="account-heading">Add Account</span><button type="button" data-close><i class="bi bi-x-lg"></i></button></header><div class="grid gap-4 p-5 sm:grid-cols-2"><label>Name:*<input name="name" required></label><label>Account Number:*<input name="account_number" required></label><label>Account Type:<select id="parent-type" name="payment_account_type_id"><option value="">Please Select</option>@foreach($types as $t)<option value="{{ $t->id }}">{{ $t->name }}</option>@endforeach</select></label><label>Account Sub Type:<select id="sub-type" name="payment_account_sub_type_id" disabled><option value="">Please Select</option></select></label><label>Opening Balance:<input name="opening_balance" type="number" step="0.01" value="0" required></label></div><div class="px-5 pb-5"><b class="text-xs">Account details</b><div class="mt-2 grid grid-cols-2 gap-3"><b class="text-xs">Label</b><b class="text-xs">Value</b>@for($i=0;$i<2;$i++)<input name="details[{{ $i }}][label]"><input name="details[{{ $i }}][value]">@endfor</div></div><footer class="flex justify-end gap-2 border-t p-4"><button class="rounded-xl bg-purple-600 px-4 py-2 text-xs font-bold text-white">Save</button><button type="button" data-close class="rounded-xl bg-slate-100 px-4 py-2 text-xs">Close</button></footer></form></dialog>
<dialog id="type-modal" class="w-[calc(100%-2rem)] max-w-xl rounded-2xl border-0 p-0 shadow-2xl"><form id="type-form" method="POST" action="{{ route('payment-accounts.types.store') }}">@csrf<input name="_method" value="POST" type="hidden"><header class="flex justify-between border-b bg-purple-50 px-5 py-4 font-bold text-purple-900"><span id="type-heading">Add account type</span><button type="button" data-close><i class="bi bi-x-lg"></i></button></header><div class="space-y-4 p-5"><label>Name:*<input name="name" required></label><label>Parent account type:<select name="parent_id"><option value="">Please Select</option>@foreach($types as $t)<option value="{{ $t->id }}">{{ $t->name }}</option>@endforeach</select></label><p class="text-xs text-slate-500">Leave the parent empty to create a main account type.</p></div><footer class="flex justify-end gap-2 border-t p-4"><button class="rounded-xl bg-purple-600 px-4 py-2 text-xs font-bold text-white">Save</button><button type="button" data-close class="rounded-xl bg-slate-100 px-4 py-2 text-xs">Close</button></footer></form></dialog>
@include('payment-accounts.transfer-modal')
@include('payment-accounts.deposit-modal')
@endsection
@push('scripts')
<style>dialog{margin:auto}dialog::backdrop{background:rgb(15 23 42/.55)}dialog label{display:block;font-size:.75rem;font-weight:700;color:#334155}dialog input,dialog select{display:block;width:100%;margin-top:.35rem;border:1px solid #cbd5e1;border-radius:.65rem;padding:.6rem .7rem;font-size:.875rem}</style>
<script>document.addEventListener('DOMContentLoaded',()=>{const csrf=document.querySelector('meta[name="csrf-token"]').content;const toast=(m,bad=false)=>{let e=document.getElementById('payment-toast');if(!e){e=document.createElement('div');e.id='payment-toast';e.className='fixed right-5 top-20 z-50 rounded-xl px-4 py-3 text-sm font-bold text-white shadow-lg';document.body.append(e)}e.className='fixed right-5 top-20 z-50 rounded-xl px-4 py-3 text-sm font-bold text-white shadow-lg '+(bad?'bg-rose-500':'bg-emerald-500');e.textContent=m;setTimeout(()=>e.remove(),3500)};const refresh=async(panel)=>{let d=new DOMParser().parseFromString(await fetch(location.href,{headers:{'X-Requested-With':'XMLHttpRequest'}}).then(r=>r.text()),'text/html');document.getElementById(panel).innerHTML=d.getElementById(panel).innerHTML};document.addEventListener('click',async e=>{let b=e.target.closest('.delete-item');if(b){if(!confirm(b.dataset.message))return;let r=await fetch(b.dataset.url,{method:'DELETE',headers:{'X-CSRF-TOKEN':csrf,'Accept':'application/json'}}),j=await r.json();if(!r.ok)return toast(j.message,true);await refresh(b.closest('#types')?'types':'accounts');toast(j.message);return}b=e.target.closest('.tab');if(b){let isTypes=b.dataset.panel==='types';document.getElementById('accounts').classList.toggle('hidden',isTypes);document.getElementById('types').classList.toggle('hidden',!isTypes);document.querySelectorAll('.tab').forEach(x=>{x.classList.toggle('border-purple-600',x===b);x.classList.toggle('border-transparent',x!==b)});return}});document.querySelectorAll('#account-form,#type-form').forEach(f=>f.addEventListener('submit',async e=>{e.preventDefault();let r=await fetch(f.action,{method:'POST',headers:{'X-CSRF-TOKEN':csrf,'Accept':'application/json'},body:new FormData(f)}),j=await r.json();if(!r.ok)return toast(j.message||'Please correct the form.',true);f.closest('dialog').close();await refresh(f.id==='type-form'?'types':'accounts');toast(j.message)}));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close())})</script>
@endpush
@push('scripts')
<script>document.addEventListener('click',async event=>{const button=event.target.closest('.close-account');if(!button)return;const confirmation=document.getElementById('close-confirm');document.getElementById('close-confirm').querySelector('h3').textContent='Close '+button.dataset.name+'?';const accepted=await new Promise(resolve=>{const yes=document.getElementById('close-ok'),no=document.getElementById('close-cancel');const finish=value=>{yes.onclick=null;no.onclick=null;confirmation.close();resolve(value)};yes.onclick=()=>finish(true);no.onclick=()=>finish(false);confirmation.showModal()});if(!accepted)return;const response=await fetch(button.dataset.url,{method:'PUT',headers:{'X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content,Accept:'application/json'}});const result=await response.json();if(!response.ok){alert(result.message||'Unable to close account.');return}const page=await fetch(location.href),doc=new DOMParser().parseFromString(await page.text(),'text/html');document.getElementById('accounts').innerHTML=doc.getElementById('accounts').innerHTML;document.getElementById('account-state').value='active';document.getElementById('account-state').dispatchEvent(new Event('change',{bubbles:true}));});</script>
@endpush
@push('scripts')
<script>document.addEventListener('click',e=>{const a=e.target.closest('#add-account,.edit-account'),t=e.target.closest('#add-type,.edit-type');if(a){const f=document.getElementById('account-form'),v=a.dataset.a?JSON.parse(a.dataset.a):null;f.reset();f.action=a.dataset.url||@json(route('payment-accounts.store'));f.elements._method.value=v?'PUT':'POST';
document.getElementById('account-heading').textContent=v?'Edit Account':'Add Account';
f.querySelector('footer button:not([type="button"])').textContent=v?'Update':'Save';
const sub=f.elements.payment_account_sub_type_id;
sub.replaceChildren(new Option('Please Select',''));
sub.disabled=true;
if(v){
    ['name','account_number','payment_account_type_id','opening_balance'].forEach(k=>f.elements[k].value=v[k]??'');
    if(v.sub_type){
        sub.add(new Option(v.sub_type.name,v.sub_type.id));
        sub.disabled=false;
        sub.value=v.payment_account_sub_type_id;
    }
    (v.details||[]).slice(0,2).forEach((detail,i)=>{
        f.elements['details['+i+'][label]'].value=detail.label;
        f.elements['details['+i+'][value]'].value=detail.value;
    });
}
document.getElementById('account-modal').showModal()}if(t){const f=document.getElementById('type-form'),v=t.dataset.t?JSON.parse(t.dataset.t):null;f.reset();f.action=v?@json(url('/payment-accounts/types'))+'/'+v.id:@json(route('payment-accounts.types.store'));f.elements._method.value=v?'PUT':'POST';if(v){f.elements.name.value=v.name;f.elements.parent_id.value=v.parent_id||''}document.getElementById('type-modal').showModal()}})</script>
@endpush
@push('scripts')
<script>document.addEventListener('DOMContentLoaded',()=>{const syncTypes=async()=>{const html=await fetch(@json(route('payment-accounts.index')),{headers:{'X-Requested-With':'XMLHttpRequest'}}).then(r=>r.text()),doc=new DOMParser().parseFromString(html,'text/html');[['#type-form select[name="parent_id"]','#type-form select[name="parent_id"]'],['#parent-type','#parent-type']].forEach(([target,source])=>{const current=document.querySelector(target),fresh=doc.querySelector(source);if(!current||!fresh)return;const selected=current.value;current.innerHTML=fresh.innerHTML;current.value=selected})};['mousedown','focus'].forEach(event=>{document.querySelector('#type-form select[name="parent_id"]').addEventListener(event,syncTypes);document.getElementById('parent-type').addEventListener(event,syncTypes)})})</script>
@endpush
@push('scripts')
<script>document.addEventListener('DOMContentLoaded',()=>{const parent=document.getElementById('parent-type'),sub=document.getElementById('sub-type');parent.addEventListener('change',async()=>{sub.innerHTML='<option value="">Loading…</option>';sub.disabled=true;const roots=await fetch(@json(route('payment-accounts.types.options'))).then(r=>r.json());const selected=roots.find(type=>String(type.id)===String(parent.value));const children=selected?.children??[];sub.innerHTML='<option value="">Please Select</option>'+children.map(type=>'<option value="'+type.id+'">'+type.name+'</option>').join('');sub.disabled=children.length===0})})</script>
@endpush
@push('scripts')
<script>document.addEventListener('DOMContentLoaded',()=>{const filter=()=>{const state=document.getElementById('account-state')?.value||'all',term=(document.getElementById('account-search')?.value||'').toLowerCase();let total=0;document.querySelectorAll('.account-row').forEach(row=>{const visible=(state==='all'||row.dataset.state===state)&&row.textContent.toLowerCase().includes(term);row.hidden=!visible;if(visible){const balance=(row.children[4]?.textContent||'').replace(/,/g,'').match(/-?\d+(?:\.\d+)?/);total+=balance?Number(balance[0]):0}});const cell=document.querySelector('#accounts tfoot td:nth-child(2)');if(cell)cell.textContent='Rs. '+total.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})};document.addEventListener('change',e=>{if(e.target.id==='account-state')filter()});document.addEventListener('input',e=>{if(e.target.id==='account-search')filter()});new MutationObserver(filter).observe(document.getElementById('accounts'),{childList:true});filter()})</script>
@endpush
@push('scripts')
<script>document.addEventListener('click',async e=>{const b=e.target.closest('.delete-item');if(!b)return;e.stopImmediatePropagation();if(!confirm(b.dataset.message))return;const r=await fetch(b.dataset.url,{method:'DELETE',headers:{'X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content,'Accept':'application/json'}}),j=await r.json();if(!r.ok){alert(j.message);return}const id=b.dataset.typeId;if(id)document.querySelectorAll('#parent-type option,#sub-type option,#type-form select[name="parent_id"] option').forEach(o=>{if(o.value===id)o.remove()});b.closest('tr').remove()},true)</script>
@endpush
